// Package obfheader implements time-keyed obfuscation headers for mux packets.
//
// Each mux packet is preceded by a plaintext header whose value is drawn from a
// per-connection pool generated by a PCG32 PRNG seeded with:
//
//	epoch = (uint64(utcSec) + k) / 86400 / 16
//	v = SHA256(uint64be(epoch))[:8] ^ k2
//
// where k and k2 are the high and low uint64 values from
// PBKDF2-HMAC-SHA256(key, Salt, 1024, 16).
// The pool changes every 16 days, providing a time-limited authentication token that
// the server can verify without a prior round-trip.
package obfheader

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/binary"
	"math"
	"math/bits"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"blackhole/pkg/constants"

	"golang.org/x/crypto/pbkdf2"
)

// HeaderType controls the deterministic bytes used in generated header prefixes.
type HeaderType string

const (
	HeaderTypePrintable HeaderType = "printable"
	HeaderTypeAny       HeaderType = "any"
	HeaderTypeUpper     HeaderType = "ALPHABET"
	HeaderTypeTitle     HeaderType = "Alphabet"
	HeaderTypeLower     HeaderType = "alphabet"
	HeaderTypeAlnum     HeaderType = "alnum"
)

// ParseHeaderType validates a config value. Empty means printable for backward compatibility.
func ParseHeaderType(value string) (HeaderType, bool) {
	switch strings.TrimSpace(value) {
	case "", string(HeaderTypePrintable):
		return HeaderTypePrintable, true
	case string(HeaderTypeAny):
		return HeaderTypeAny, true
	case string(HeaderTypeUpper):
		return HeaderTypeUpper, true
	case string(HeaderTypeTitle):
		return HeaderTypeTitle, true
	case string(HeaderTypeLower):
		return HeaderTypeLower, true
	case string(HeaderTypeAlnum):
		return HeaderTypeAlnum, true
	default:
		return "", false
	}
}

// ── PCG32 ─────────────────────────────────────────────────────────────────────

const (
	pcgMult       = uint64(6364136223846793005)
	pcgDefaultSeq = uint64(0xda3e39cb94b95bdb)
)

type pcg32 struct {
	state uint64
	inc   uint64
}

func newPCG32(seed uint64) pcg32 {
	var p pcg32
	p.seedRNG(seed, pcgDefaultSeq)
	return p
}

func (p *pcg32) seedRNG(seed, seq uint64) {
	p.state = 0
	p.inc = (seq << 1) | 1
	p.next()
	p.state += seed
	p.next()
}

func (p *pcg32) next() uint32 {
	oldstate := p.state
	p.state = oldstate*pcgMult + p.inc
	xorshifted := uint32(((oldstate >> 18) ^ oldstate) >> 27)
	rot := uint32(oldstate >> 59)
	return bits.RotateLeft32(xorshifted, -int(rot))
}

// ── Key derivation ────────────────────────────────────────────────────────────

// DeriveK derives the 64-bit key components k and k2 from the global server key.
// Uses PBKDF2-HMAC-SHA256(key, Salt, 1024, 16), split into two big-endian uint64 values.
func DeriveK(key string) (uint64, uint64) {
	derived := pbkdf2.Key([]byte(key), []byte(constants.Salt), constants.ServerKeyDerivationIterations, 16, sha256.New)
	return binary.BigEndian.Uint64(derived[:8]), binary.BigEndian.Uint64(derived[8:])
}

// ComputeEpoch returns the raw ordered 16-day epoch used before hashing into v.
func ComputeEpoch(k uint64, utcSec int64) uint64 {
	return computeEpoch(k, utcSec)
}

// ComputeV computes the PCG32 seed from a hashed 16-day epoch XORed with k2.
// The epoch changes every 16 days.
func ComputeV(k, k2 uint64, utcSec int64) uint64 {
	epoch := computeEpoch(k, utcSec)
	return computeVFromEpoch(epoch, k2)
}

// ComputeVFromEpoch transforms a raw ordered epoch into the obfuscation seed v.
func ComputeVFromEpoch(epoch, k2 uint64) uint64 {
	return computeVFromEpoch(epoch, k2)
}

func computeEpoch(k uint64, utcSec int64) uint64 {
	return (uint64(utcSec) + k) / 86400 / 16
}

func computeVFromEpoch(epoch, k2 uint64) uint64 {
	var b [8]byte
	binary.BigEndian.PutUint64(b[:], epoch)
	sum := sha256.Sum256(b[:])
	return binary.BigEndian.Uint64(sum[:8]) ^ k2
}

// ── Header pool ───────────────────────────────────────────────────────────────

// header is a (Len, Head) pair. The first Len bytes of any matching obfuscation
// header must equal Head; the remaining bytes are random.
type header struct {
	Len       int    // number of significant bytes
	Head      []byte // Len bytes, stored little-endian (low byte first)
	LenOffset uint16 // deterministic length-field subtraction for this magic
}

// Pool holds all derived headers for one connection epoch.
type Pool struct {
	HandshakeHeader  header   // dedicated client handshake header
	DataMagicLen     int      // deterministic magic span for later packet headers
	DataHeaderHasLen bool     // whether later packet headers carry a 2-byte plaintext len value after magic
	DataHeaderHasID  bool     // whether later packet headers carry a 2-byte plaintext packet id after magic
	Threshold        int      // payload-size boundary for large/small classification
	SmallGroup       []header // data headers for small packets (first N/2 headers)
	LargeGroup       []header // data headers for large packets (last N-N/2 headers)
	PaddingThreshold []int    // sorted lower-bound thresholds for deterministic padding buckets
	PaddingSize      [2][constants.PaddingBucketCount]uint16
	PaddingRowLimit  [constants.PaddingBucketCount]int
	MinPadding       uint16    // minimum random padding for special/empty packets
	MaxPadding       uint16    // maximum random padding for special/empty packets
	smallCDF         []float64 // precomputed power-law CDF for SmallGroup (α=0.7)
	largeCDF         []float64 // precomputed power-law CDF for LargeGroup (α=1.5)
	dataHeaderSet    map[string]struct{}
	dataLenOffsets   map[string]uint16
	dataFields       []handshakeFieldKind
}

type versionKind uint8

const (
	versionNone versionKind = iota
	versionUint32
	versionInt16Triple
	versionString
)

type handshakeFieldKind uint8

const (
	handshakeFieldLen handshakeFieldKind = iota
	handshakeFieldFixID
	handshakeFieldEpochID
	handshakeFieldClientID
	handshakeFieldIncID
	handshakeFieldPacketID
	handshakeFieldUTC
	handshakeFieldID1
	handshakeFieldID2
)

type handshakeField struct {
	Kind  handshakeFieldKind
	Size  int
	Value uint32
}

type handshakeLayout struct {
	MagicLen        int
	VersionKind     versionKind
	VersionLen      int
	VersionSegments [3]int
	LenOffset       uint16
	Fields          []handshakeField
	DataMagicLen    int
	DataHasLen      bool
	DataHasID       bool
	DataFields      []handshakeFieldKind
}

// HandshakeContext carries values that are encoded into the 32-byte first header.
type HandshakeContext struct {
	RawEpoch         uint64
	TimestampPadding uint16
	ClientID         uint32
	IncID            uint32
	PacketID         uint16
	UTCSeconds       uint32
}

// HandshakeInfo contains parsed first-header information needed by mux.
type HandshakeInfo struct {
	HasTimestampPaddingLen bool
	TimestampPaddingLen    uint16
}

type handshakeLayoutCacheKey string

var handshakeLayoutCache = struct {
	sync.Mutex
	layouts map[handshakeLayoutCacheKey]*handshakeLayout
}{
	layouts: make(map[handshakeLayoutCacheKey]*handshakeLayout),
}

// GeneratePool builds a Pool from seed v using a deterministic PCG32 sequence.
//
// Generation order (matches the spec exactly):
//  1. Handshake magic bytes
//  2. N  ∈ [16, 80)
//  3. threshold ∈ [64, 512]
//  4. N data headers
//  5. deterministic padding threshold table
//  6. deterministic padding size table
//  7. padding row selection limit table
//  8. minimum special-packet padding
//  9. maximum special-packet padding
func GeneratePool(v uint64) *Pool {
	return GeneratePoolWithType(v, HeaderTypePrintable)
}

// GeneratePoolWithType builds a Pool from seed v and a configured header type.
func GeneratePoolWithType(v uint64, headerType HeaderType) *Pool {
	return GeneratePoolWithKey(v, headerType, "")
}

// GeneratePoolWithKey builds a Pool using the epoch seed and server-key-derived header layout.
func GeneratePoolWithKey(v uint64, headerType HeaderType, serverKey string) *Pool {
	rng := newPCG32(v)
	if headerType != HeaderTypeAny &&
		headerType != HeaderTypeUpper &&
		headerType != HeaderTypeTitle &&
		headerType != HeaderTypeLower &&
		headerType != HeaderTypeAlnum {
		headerType = HeaderTypePrintable
	}
	layout := getHandshakeLayout(serverKey)

	// 1. Handshake magic bytes
	hsLen := constants.HandshakeObfMagicMaxLen
	hsHead := rngBytes(&rng, hsLen, headerType)
	hsLenOffset := uint16(rng.next() % 65)

	// 2 & 3. N and threshold
	n := int(rng.next()%64) + 16          // [16, 80)
	threshold := int(rng.next()%449) + 64 // [64, 512]

	// 4. N data headers
	dataHdrs := make([]header, n)
	seenDataHeaders := make(map[string]struct{}, n)
	for i := range dataHdrs {
		for {
			hlen := randomHeaderLen(&rng, constants.DataObfHeaderMinLen, layout.DataMagicLen)
			head := make([]byte, layout.DataMagicLen)
			copy(head, rngBytes(&rng, hlen, headerType))
			h := header{Len: layout.DataMagicLen, Head: head, LenOffset: uint16(rng.next() % 18)}
			key := string(h.Head[:h.Len])
			if _, exists := seenDataHeaders[key]; exists {
				continue
			}
			seenDataHeaders[key] = struct{}{}
			dataHdrs[i] = h
			break
		}
	}
	half := n / 2
	small := dataHdrs[:half]
	large := dataHdrs[half:]
	paddingThreshold, paddingSize, paddingRowLimit, minPadding, maxPadding := generatePaddingTables(&rng)
	dataHeaderSet := make(map[string]struct{}, len(dataHdrs))
	dataLenOffsets := make(map[string]uint16, len(dataHdrs))
	for _, h := range dataHdrs {
		key := string(h.Head[:h.Len])
		dataHeaderSet[key] = struct{}{}
		dataLenOffsets[key] = h.LenOffset
	}

	return &Pool{
		HandshakeHeader:  header{Len: hsLen, Head: hsHead, LenOffset: hsLenOffset},
		DataMagicLen:     layout.DataMagicLen,
		DataHeaderHasLen: layout.DataHasLen,
		DataHeaderHasID:  layout.DataHasID,
		Threshold:        threshold,
		SmallGroup:       small,
		LargeGroup:       large,
		PaddingThreshold: paddingThreshold,
		PaddingSize:      paddingSize,
		PaddingRowLimit:  paddingRowLimit,
		MinPadding:       minPadding,
		MaxPadding:       maxPadding,
		smallCDF:         buildCDF(small, 0.7),
		largeCDF:         buildCDF(large, 1.5),
		dataHeaderSet:    dataHeaderSet,
		dataLenOffsets:   dataLenOffsets,
		dataFields:       append([]handshakeFieldKind(nil), layout.DataFields...),
	}
}

func randomHeaderLen(rng *pcg32, minLen, maxLen int) int {
	return int(rng.next()%uint32(maxLen-minLen+1)) + minLen
}

func getHandshakeLayout(serverKey string) *handshakeLayout {
	cacheKey := handshakeLayoutCacheKey(serverKey)
	handshakeLayoutCache.Lock()
	if layout := handshakeLayoutCache.layouts[cacheKey]; layout != nil {
		handshakeLayoutCache.Unlock()
		return layout
	}
	handshakeLayoutCache.Unlock()

	layout := generateHandshakeLayout(serverKey)

	handshakeLayoutCache.Lock()
	if cached := handshakeLayoutCache.layouts[cacheKey]; cached != nil {
		handshakeLayoutCache.Unlock()
		return cached
	}
	handshakeLayoutCache.layouts[cacheKey] = layout
	handshakeLayoutCache.Unlock()
	return layout
}

func generateHandshakeLayout(serverKey string) *handshakeLayout {
	sum := sha256.Sum256([]byte(serverKey))
	var rng pcg32
	rng.seedRNG(binary.BigEndian.Uint64(sum[:8]), binary.BigEndian.Uint64(sum[8:16]))

	layout := &handshakeLayout{
		MagicLen:    randomHeaderLen(&rng, constants.HandshakeObfHeaderMinLen, constants.HandshakeObfMagicMaxLen),
		VersionKind: versionKind(rng.next() % 4),
	}
	for i := range layout.VersionSegments {
		layout.VersionSegments[i] = int(rng.next()%2) + 1
	}
	if layout.VersionKind == versionString {
		layout.VersionLen = int(rng.next()%4) + 5
	} else {
		switch layout.VersionKind {
		case versionUint32:
			layout.VersionLen = 4
		case versionInt16Triple:
			layout.VersionLen = 6
		default:
			layout.VersionLen = 0
		}
	}

	candidates := []handshakeFieldKind{
		handshakeFieldLen,
		handshakeFieldFixID,
		handshakeFieldEpochID,
		handshakeFieldClientID,
		handshakeFieldIncID,
		handshakeFieldPacketID,
		handshakeFieldUTC,
		handshakeFieldID1,
		handshakeFieldID2,
	}
	for i := range candidates {
		j := i + int(rng.next()%uint32(len(candidates)-i))
		candidates[i], candidates[j] = candidates[j], candidates[i]
	}

	count := int(rng.next() % 4)
	layout.Fields = make([]handshakeField, 0, count)
	for _, kind := range candidates[:count] {
		field := handshakeField{Kind: kind}
		switch kind {
		case handshakeFieldLen:
			field.Size = 2
			layout.LenOffset = uint16(rng.next() % 64)
			field.Value = uint32(layout.LenOffset)
		case handshakeFieldPacketID:
			field.Size = constants.DataObfPacketIDSize
		case handshakeFieldFixID:
			field.Size = chooseSize(&rng, []int{1, 2, 4})
			field.Value = logUniformUint(&rng, field.Size)
		case handshakeFieldEpochID, handshakeFieldClientID:
			field.Size = chooseSize(&rng, []int{2, 4})
		case handshakeFieldIncID:
			field.Size = 2
		case handshakeFieldUTC:
			field.Size = 4
		case handshakeFieldID1, handshakeFieldID2:
			field.Size = chooseSize(&rng, []int{1, 2, 4})
			field.Value = logUniformUint(&rng, field.Size)
		}
		layout.Fields = append(layout.Fields, field)
	}
	layout.DataHasLen = handshakeLayoutHasField(layout, handshakeFieldLen)
	layout.DataHasID = handshakeLayoutHasField(layout, handshakeFieldPacketID)
	for _, field := range layout.Fields {
		if field.Kind == handshakeFieldLen || field.Kind == handshakeFieldPacketID {
			layout.DataFields = append(layout.DataFields, field.Kind)
		}
	}
	dataFieldBytes := len(layout.DataFields) * constants.DataObfPacketIDSize
	dataMagicMaxLen := constants.DataObfHeaderSize - dataFieldBytes
	if len(layout.DataFields) > 0 && dataMagicMaxLen > 4 {
		dataMagicMaxLen = 4
	}
	layout.DataMagicLen = randomHeaderLen(&rng, constants.DataObfHeaderMinLen, dataMagicMaxLen)
	return layout
}

func handshakeLayoutHasField(layout *handshakeLayout, kind handshakeFieldKind) bool {
	for _, field := range layout.Fields {
		if field.Kind == kind {
			return true
		}
	}
	return false
}

func chooseSize(rng *pcg32, sizes []int) int {
	return sizes[int(rng.next()%uint32(len(sizes)))]
}

func logUniformUint(rng *pcg32, size int) uint32 {
	u := float64(rng.next()) / (float64(math.MaxUint32) + 1)
	maxExclusive := 1 << uint(size*8)
	return uint32(logUniformExclusive(u, 10, maxExclusive+10) - 10)
}

func generatePaddingTables(rng *pcg32) ([]int, [2][constants.PaddingBucketCount]uint16, [constants.PaddingBucketCount]int, uint16, uint16) {
	valuesLen := constants.NoPaddingThreshold - constants.MinPacketSize + 1
	values := make([]int, valuesLen)
	for i := range values {
		values[i] = constants.MinPacketSize + i
	}
	for i := 0; i < constants.PaddingShuffleCount; i++ {
		j := i + int(rng.next()%uint32(len(values)-i))
		values[i], values[j] = values[j], values[i]
	}
	selected := append([]int(nil), values[:constants.PaddingShuffleCount]...)
	sort.Ints(selected)

	thresholds := make([]int, constants.PaddingBucketCount)
	for i, value := range selected {
		thresholds[i+1] = value
	}

	var paddingSize [2][constants.PaddingBucketCount]uint16
	for row := range paddingSize {
		for i := range paddingSize[row] {
			paddingSize[row][i] = pcgLogUniformRange(rng, 0, constants.MaxDataPaddingSize)
		}
	}
	var paddingRowLimit [constants.PaddingBucketCount]int
	for i := range paddingRowLimit {
		paddingRowLimit[i] = int(rng.next() % 128)
	}
	minPadding := uint16(constants.MinPaddingMin + int(byte(rng.next())))
	maxPadding := uint16(constants.MaxPaddingMin + int(rng.next()%uint32(constants.MaxPaddingMax-constants.MaxPaddingMin+1)))
	return thresholds, paddingSize, paddingRowLimit, minPadding, maxPadding
}

func pcgLogUniformRange(rng *pcg32, min, max int) uint16 {
	if max <= min {
		return uint16(min)
	}
	u := float64(rng.next()) / (float64(math.MaxUint32) + 1)
	return uint16(logUniformInclusive(u, min, max))
}

func logUniformInclusive(u float64, min, max int) int {
	if min <= 0 {
		offset := constants.PaddingLogOffset
		return logUniformExclusive(u, min+offset, max+1+offset) - offset
	}
	return logUniformExclusive(u, min, max+1)
}

func logUniformExclusive(u float64, minInclusive, maxExclusive int) int {
	if maxExclusive <= minInclusive {
		return minInclusive
	}
	value := int(math.Floor(math.Exp(u*(math.Log(float64(maxExclusive))-math.Log(float64(minInclusive))) + math.Log(float64(minInclusive)))))
	if value < minInclusive {
		return minInclusive
	}
	if value >= maxExclusive {
		return maxExclusive - 1
	}
	return value
}

// PaddingForPayload returns the deterministic data-channel padding size for payload.
func PaddingForPayload(pool *Pool, payload []byte) uint16 {
	if pool == nil || len(pool.PaddingThreshold) != constants.PaddingBucketCount {
		return 0
	}
	payloadLen := len(payload)
	if payloadLen == 0 {
		return 0
	}
	idx := sort.Search(len(pool.PaddingThreshold), func(i int) bool {
		return pool.PaddingThreshold[i] >= payloadLen
	})
	if idx >= constants.PaddingBucketCount {
		idx = constants.PaddingBucketCount - 1
	}
	return pool.PaddingSize[paddingSizeRow(payload[payloadLen-1], pool.PaddingRowLimit[idx])][idx]
}

func paddingSizeRow(lastPayloadByte byte, rowLimit int) int {
	if rowLimit < 0 {
		rowLimit = 0
	}
	if rowLimit > 256 {
		rowLimit = 256
	}
	if int(lastPayloadByte) <= rowLimit {
		return 0
	}
	return 1
}

func rngBytes(rng *pcg32, n int, headerType HeaderType) []byte {
	out := make([]byte, n)
	for i := range out {
		switch headerType {
		case HeaderTypeAny:
			out[i] = byte(rng.next())
		case HeaderTypeUpper:
			out[i] = byte(rng.next()%26) + 'A'
		case HeaderTypeTitle:
			if i == 0 {
				out[i] = byte(rng.next()%26) + 'A'
			} else {
				out[i] = byte(rng.next()%26) + 'a'
			}
		case HeaderTypeLower:
			out[i] = byte(rng.next()%26) + 'a'
		case HeaderTypeAlnum:
			const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
			out[i] = alphabet[int(rng.next())%len(alphabet)]
		default:
			out[i] = byte(rng.next()%0x5e) + 0x21
		}
	}
	return out
}

// buildCDF returns a normalised cumulative distribution for hdrs with power-law
// weights w_i = (i+1)^(-alpha).
func buildCDF(hdrs []header, alpha float64) []float64 {
	n := len(hdrs)
	if n == 0 {
		return nil
	}
	total := 0.0
	for i := 0; i < n; i++ {
		total += math.Pow(float64(i+1), -alpha)
	}
	cdf := make([]float64, n)
	acc := 0.0
	for i := 0; i < n; i++ {
		acc += math.Pow(float64(i+1), -alpha) / total
		cdf[i] = acc
	}
	return cdf
}

// sampleCDF returns the index for a uniform random value r ∈ [0, 1).
func sampleCDF(cdf []float64, r float64) int {
	idx := sort.Search(len(cdf), func(i int) bool { return cdf[i] >= r })
	if idx >= len(cdf) {
		idx = len(cdf) - 1
	}
	return idx
}

// randFloat returns a uniform float64 in [0, 1) using crypto/rand.
func randFloat() float64 {
	var b [4]byte
	rand.Read(b[:]) //nolint:errcheck
	// Divide by 2^32 to get [0, 1)
	return float64(binary.BigEndian.Uint32(b[:])) / 4294967296.0
}

// ── Header selection (sender side) ───────────────────────────────────────────

// SelectHandshakeHeader returns a first-packet plaintext prefix using a default
// empty-key layout. Production callers should use SelectHandshakeHeaderWithContext.
func SelectHandshakeHeader(pool *Pool, v uint64) []byte {
	return SelectHandshakeHeaderWithContext(pool, v, "", HandshakeContext{})
}

// SelectHandshakeHeaderWithContext returns the first-packet plaintext prefix:
// 32-byte obfuscation head + 8-byte HMAC keyed by v.
func SelectHandshakeHeaderWithContext(pool *Pool, v uint64, serverKey string, ctx HandshakeContext) []byte {
	hdr := make([]byte, constants.HandshakeObfHeaderSize)
	rand.Read(hdr) //nolint:errcheck
	layout := getHandshakeLayout(serverKey)
	writeHandshakeHead(hdr, pool, layout, ctx)

	prefix := make([]byte, constants.HandshakeObfPrefixSize)
	copy(prefix, hdr)
	copy(prefix[constants.HandshakeObfHeaderSize:], handshakeHeaderAuth(v, hdr))
	return prefix
}

func HandshakeHeaderLenValue(pool *Pool, wireSize uint16) uint16 {
	if pool == nil {
		return wireSize
	}
	return HeaderLenValueWithOffset(wireSize, pool.HandshakeHeader.LenOffset)
}

// HandshakeHeaderBoundarySize reverses HandshakeHeaderLenValue and returns the
// distance from the handshake header to the next obfuscation header.
func HandshakeHeaderBoundarySize(pool *Pool, lenValue uint16) (uint16, bool) {
	if pool == nil {
		return lenValue, true
	}
	return addHeaderLenOffset(lenValue, pool.HandshakeHeader.LenOffset)
}

func HeaderLenValueWithOffset(wireSize, offset uint16) uint16 {
	if offset > wireSize {
		return 0
	}
	return wireSize - offset
}

func writeHandshakeHead(hdr []byte, pool *Pool, layout *handshakeLayout, ctx HandshakeContext) {
	copy(hdr[:layout.MagicLen], pool.HandshakeHeader.Head[:layout.MagicLen])

	offset := layout.MagicLen
	writeVersion(hdr[offset:offset+layout.VersionLen], layout, ctx.RawEpoch)
	offset += layout.VersionLen

	for _, field := range layout.Fields {
		if offset+field.Size > len(hdr) {
			return
		}
		writeHandshakeField(hdr[offset:offset+field.Size], field, layout, ctx)
		offset += field.Size
	}
}

func writeVersion(dst []byte, layout *handshakeLayout, epoch uint64) {
	switch layout.VersionKind {
	case versionUint32:
		binary.BigEndian.PutUint32(dst, uint32(epoch))
	case versionInt16Triple:
		segments := epochDecimalSegments(epoch, layout.VersionSegments)
		for i, segment := range segments {
			binary.BigEndian.PutUint16(dst[i*2:i*2+2], uint16(segment))
		}
	case versionString:
		for i := range dst {
			dst[i] = 0
		}
		copy(dst, []byte(epochVersionString(epoch, layout.VersionSegments)))
	}
}

func writeHandshakeField(dst []byte, field handshakeField, layout *handshakeLayout, ctx HandshakeContext) {
	var value uint32
	switch field.Kind {
	case handshakeFieldLen:
		value = uint32(ctx.TimestampPadding) + uint32(layout.LenOffset)
	case handshakeFieldFixID, handshakeFieldID1, handshakeFieldID2:
		value = field.Value
	case handshakeFieldEpochID:
		value = uint32(ctx.RawEpoch)
	case handshakeFieldClientID:
		value = ctx.ClientID
	case handshakeFieldIncID:
		value = ctx.IncID
	case handshakeFieldPacketID:
		value = uint32(ctx.PacketID)
	case handshakeFieldUTC:
		value = ctx.UTCSeconds
	}
	writeUintBE(dst, value)
}

func epochDecimalSegments(epoch uint64, lens [3]int) [3]int {
	total := 0
	for _, l := range lens {
		total += l
	}
	divisor := uint64(1)
	for i := 0; i < total; i++ {
		divisor *= 10
	}
	digits := strconv.FormatUint(epoch%divisor, 10)
	for len(digits) < total {
		digits = "0" + digits
	}

	var out [3]int
	offset := 0
	for i, l := range lens {
		n, _ := strconv.Atoi(digits[offset : offset+l])
		out[i] = n
		offset += l
	}
	return out
}

func epochVersionString(epoch uint64, lens [3]int) string {
	segments := epochDecimalSegments(epoch, lens)
	parts := make([]string, len(segments))
	for i, segment := range segments {
		parts[i] = strconv.Itoa(segment)
	}
	return strings.Join(parts, ".")
}

func writeUintBE(dst []byte, value uint32) {
	switch len(dst) {
	case 1:
		dst[0] = byte(value)
	case 2:
		binary.BigEndian.PutUint16(dst, uint16(value))
	case 4:
		binary.BigEndian.PutUint32(dst, value)
	}
}

// DataHeaderContext carries dynamic values encoded into a later-packet header.
type DataHeaderContext struct {
	LenValue uint16
	WireSize uint16
	PacketID uint16
}

// SelectHeader picks a data header for a packet of the given payload size.
// Group selection uses a sigmoid on (payloadSize − threshold) / (threshold × 0.2);
// within the chosen group, an index is sampled from the power-law CDF. lenValue
// is written into the optional later-header len field when that field exists.
func SelectHeader(pool *Pool, payloadSize int, lenValue uint16) []byte {
	return SelectHeaderWithContext(pool, payloadSize, DataHeaderContext{LenValue: lenValue})
}

// SelectHeaderWithContext picks a data header and writes optional data-header fields.
func SelectHeaderWithContext(pool *Pool, payloadSize int, ctx DataHeaderContext) []byte {
	kSigmoid := float64(pool.Threshold) * 0.2
	pLarge := 1.0 / (1.0 + math.Exp(-float64(payloadSize-pool.Threshold)/kSigmoid))

	var group []header
	var cdf []float64
	if randFloat() < pLarge {
		group = pool.LargeGroup
		cdf = pool.largeCDF
	} else {
		group = pool.SmallGroup
		cdf = pool.smallCDF
	}

	idx := sampleCDF(cdf, randFloat())
	h := group[idx]
	lenValue := ctx.LenValue
	if ctx.WireSize > 0 {
		lenOffset := h.LenOffset
		if pool.dataLenOffsets != nil {
			if mapped, ok := pool.dataLenOffsets[string(h.Head[:h.Len])]; ok {
				lenOffset = mapped
			}
		}
		lenValue = HeaderLenValueWithOffset(ctx.WireSize, lenOffset)
	}

	hdr := make([]byte, constants.DataObfHeaderSize)
	copy(hdr[:h.Len], h.Head)
	offset := h.Len
	for _, field := range pool.dataFields {
		switch field {
		case handshakeFieldLen:
			binary.BigEndian.PutUint16(hdr[offset:offset+constants.PacketLengthSize], lenValue)
			offset += constants.PacketLengthSize
		case handshakeFieldPacketID:
			binary.BigEndian.PutUint16(hdr[offset:offset+constants.DataObfPacketIDSize], ctx.PacketID)
			offset += constants.DataObfPacketIDSize
		}
	}
	rand.Read(hdr[offset:]) //nolint:errcheck
	return hdr
}

func DataHeaderLenValue(pool *Pool, hdr []byte, wireSize uint16) (uint16, bool) {
	if pool == nil || len(hdr) < pool.DataMagicLen {
		return 0, false
	}
	offset, ok := pool.dataLenOffsets[string(hdr[:pool.DataMagicLen])]
	if !ok {
		return 0, false
	}
	return HeaderLenValueWithOffset(wireSize, offset), true
}

// DataHeaderBoundarySize reads the optional data-header len field and returns
// the distance from this header to the next obfuscation header.
func DataHeaderBoundarySize(pool *Pool, hdr []byte) (uint16, bool) {
	if pool == nil || !pool.DataHeaderHasLen || len(hdr) < pool.DataMagicLen {
		return 0, false
	}
	fieldOffset, ok := DataHeaderLenOffset(pool)
	if !ok || len(hdr) < fieldOffset+constants.PacketLengthSize {
		return 0, false
	}
	lenOffset, ok := pool.dataLenOffsets[string(hdr[:pool.DataMagicLen])]
	if !ok {
		return 0, false
	}
	value := binary.BigEndian.Uint16(hdr[fieldOffset : fieldOffset+constants.PacketLengthSize])
	return addHeaderLenOffset(value, lenOffset)
}

func addHeaderLenOffset(value, offset uint16) (uint16, bool) {
	size := uint32(value) + uint32(offset)
	if size > uint32(^uint16(0)) {
		return 0, false
	}
	return uint16(size), true
}

// ValidateHeaderPaddingLen reports whether the optional data-header len value
// matches the selected magic header and expected next-header boundary size.
func ValidateHeaderPaddingLen(pool *Pool, hdr []byte, wireSize uint16) bool {
	if pool == nil || !pool.DataHeaderHasLen {
		return true
	}
	offset, ok := DataHeaderLenOffset(pool)
	if !ok {
		return true
	}
	if len(hdr) < offset+constants.PacketLengthSize {
		return false
	}
	value := binary.BigEndian.Uint16(hdr[offset : offset+constants.PacketLengthSize])
	expected, ok := DataHeaderLenValue(pool, hdr, wireSize)
	return ok && value == expected
}

// DataHeaderLenOffset returns the offset of the optional later-header len field.
func DataHeaderLenOffset(pool *Pool) (int, bool) {
	return dataFieldOffset(pool, handshakeFieldLen)
}

// DataHeaderPacketIDOffset returns the offset of the optional later-header packet-id field.
func DataHeaderPacketIDOffset(pool *Pool) (int, bool) {
	return dataFieldOffset(pool, handshakeFieldPacketID)
}

func dataFieldOffset(pool *Pool, kind handshakeFieldKind) (int, bool) {
	if pool == nil {
		return 0, false
	}
	offset := pool.DataMagicLen
	for _, field := range pool.dataFields {
		switch field {
		case handshakeFieldLen:
			if kind == field {
				return offset, true
			}
			offset += constants.PacketLengthSize
		case handshakeFieldPacketID:
			if kind == field {
				return offset, true
			}
			offset += constants.DataObfPacketIDSize
		}
	}
	return 0, false
}

// ── Header validation (receiver side) ────────────────────────────────────────

// ValidateHeader reports whether hdr matches any data header (small or large group).
func ValidateHeader(pool *Pool, hdr []byte) bool {
	if pool == nil || len(hdr) < pool.DataMagicLen {
		return false
	}
	if pool.dataHeaderSet != nil {
		_, ok := pool.dataHeaderSet[string(hdr[:pool.DataMagicLen])]
		return ok
	}
	for _, h := range pool.SmallGroup {
		if matchHeader(h, hdr) {
			return true
		}
	}
	for _, h := range pool.LargeGroup {
		if matchHeader(h, hdr) {
			return true
		}
	}
	return false
}

// ValidateHandshakeHeader reports whether hdr matches the pool's handshake header.
func ValidateHandshakeHeader(pool *Pool, hdr []byte) bool {
	return matchHeader(pool.HandshakeHeader, hdr)
}

func matchHeader(h header, hdr []byte) bool {
	if len(hdr) < h.Len {
		return false
	}
	for i := 0; i < h.Len; i++ {
		if hdr[i] != h.Head[i] {
			return false
		}
	}
	return true
}

// ── Server-side pool derivation ───────────────────────────────────────────────

type poolCacheKey struct {
	password   string
	headerType HeaderType
}

type cachedPool struct {
	epoch uint64
	v     uint64
	pool  *Pool
}

type handshakePoolCacheEntry struct {
	sync.Mutex
	byV map[uint64]*Pool
}

var handshakePoolCache = struct {
	sync.Mutex
	pools map[poolCacheKey]*handshakePoolCacheEntry
}{
	pools: make(map[poolCacheKey]*handshakePoolCacheEntry),
}

// FindPoolForHandshake attempts to recover the Pool for a client first-packet
// prefix. It validates the 8-byte header auth tag by trying the current
// 16-day raw epoch and its adjacent epochs, each transformed into v with k2, then
// validates the 32-byte handshake head against the matching pool and layout.
//
// Returns the matching Pool, matching v, and true on success; nil, 0, and false otherwise.
func FindPoolForHandshake(password string, rcvdHdr []byte) (*Pool, uint64, bool) {
	return FindPoolForHandshakeWithType(password, rcvdHdr, HeaderTypePrintable)
}

// FindPoolForHandshakeWithType attempts to recover the Pool for the configured header type.
func FindPoolForHandshakeWithType(password string, rcvdHdr []byte, headerType HeaderType) (*Pool, uint64, bool) {
	pool, v, _, ok := FindPoolForHandshakeWithInfo(password, rcvdHdr, headerType)
	return pool, v, ok
}

// FindPoolForHandshakeWithInfo attempts to recover the Pool and parsed handshake metadata.
func FindPoolForHandshakeWithInfo(password string, rcvdHdr []byte, headerType HeaderType) (*Pool, uint64, HandshakeInfo, bool) {
	var info HandshakeInfo
	if len(rcvdHdr) != constants.HandshakeObfPrefixSize {
		return nil, 0, info, false
	}
	k, k2 := DeriveK(password)
	hdr := rcvdHdr[:constants.HandshakeObfHeaderSize]
	epoch := computeEpoch(k, time.Now().Unix())
	layout := getHandshakeLayout(password)
	for _, candidate := range cachedHandshakePools(password, headerType, epoch, k2) {
		if !ValidateHandshakeHeaderAuth(candidate.v, rcvdHdr) {
			continue
		}
		parsed, ok := validateHandshakeHead(candidate.pool, layout, hdr, candidate.epoch)
		if ok {
			return candidate.pool, candidate.v, parsed, true
		}
	}
	return nil, 0, info, false
}

// HandshakePrefilterSize returns the deterministic leading byte count needed
// to rule out all current handshake candidates without authenticating one.
// The prefix contains the epoch-pool magic and, when present, as much of the
// deterministic epoch version as fits in the first eight bytes.
func HandshakePrefilterSize(serverKey string) int {
	layout := getHandshakeLayout(serverKey)
	size := layout.MagicLen + layout.VersionLen
	if size > constants.HandshakeObfMagicMaxLen {
		size = constants.HandshakeObfMagicMaxLen
	}
	return size
}

// MayMatchHandshakePrefix reports whether prefix could belong to the current,
// previous, or next raw epoch. It is only a fast routing prefilter; callers
// must still validate the complete handshake head and its authentication tag.
func MayMatchHandshakePrefix(serverKey string, prefix []byte, headerType HeaderType) bool {
	wantLen := HandshakePrefilterSize(serverKey)
	if len(prefix) != wantLen {
		return false
	}

	k, k2 := DeriveK(serverKey)
	epoch := computeEpoch(k, time.Now().Unix())
	layout := getHandshakeLayout(serverKey)
	for _, candidate := range cachedHandshakePools(serverKey, headerType, epoch, k2) {
		magic := candidate.pool.HandshakeHeader.Head[:layout.MagicLen]
		if !hmac.Equal(prefix[:layout.MagicLen], magic) {
			continue
		}
		versionPrefixLen := wantLen - layout.MagicLen
		if versionPrefixLen == 0 {
			return true
		}
		expectedVersion := make([]byte, layout.VersionLen)
		writeVersion(expectedVersion, layout, candidate.epoch)
		if hmac.Equal(prefix[layout.MagicLen:], expectedVersion[:versionPrefixLen]) {
			return true
		}
	}
	return false
}

func cachedHandshakePools(password string, headerType HeaderType, currentEpoch, k2 uint64) []cachedPool {
	vs := candidateHandshakeVs(currentEpoch, k2)
	keep := make(map[uint64]struct{}, len(vs))
	for _, v := range vs {
		keep[v] = struct{}{}
	}

	key := poolCacheKey{password: password, headerType: headerType}
	handshakePoolCache.Lock()
	entry := handshakePoolCache.pools[key]
	if entry == nil {
		entry = &handshakePoolCacheEntry{byV: make(map[uint64]*Pool, len(vs))}
		handshakePoolCache.pools[key] = entry
	}
	handshakePoolCache.Unlock()

	// Pool generation is relatively expensive. Serialize work only for the same
	// password/header type instead of blocking every handshake cache globally.
	entry.Lock()
	defer entry.Unlock()
	for cachedV := range entry.byV {
		if _, ok := keep[cachedV]; !ok {
			delete(entry.byV, cachedV)
		}
	}

	rawEpochs := candidateHandshakeEpochs(currentEpoch)
	candidates := make([]cachedPool, 0, len(rawEpochs))
	for _, epoch := range rawEpochs {
		v := computeVFromEpoch(epoch, k2)
		pool := entry.byV[v]
		if pool == nil {
			pool = GeneratePoolWithKey(v, headerType, password)
			entry.byV[v] = pool
		}
		candidates = append(candidates, cachedPool{epoch: epoch, v: v, pool: pool})
	}
	return candidates
}

func candidateHandshakeVs(epoch, k2 uint64) []uint64 {
	rawEpochs := candidateHandshakeEpochs(epoch)
	vs := make([]uint64, 0, len(rawEpochs))
	for _, rawEpoch := range rawEpochs {
		vs = append(vs, computeVFromEpoch(rawEpoch, k2))
	}
	return vs
}

func candidateHandshakeEpochs(epoch uint64) []uint64 {
	if epoch == 0 {
		return []uint64{0, 1}
	}
	return []uint64{
		epoch,
		epoch - 1,
		epoch + 1,
	}
}

func validateHandshakeHead(pool *Pool, layout *handshakeLayout, hdr []byte, epoch uint64) (HandshakeInfo, bool) {
	var info HandshakeInfo
	if !matchHeader(header{Len: layout.MagicLen, Head: pool.HandshakeHeader.Head[:layout.MagicLen]}, hdr) {
		return info, false
	}
	offset := layout.MagicLen
	if offset+layout.VersionLen > len(hdr) {
		return info, false
	}
	if !validateVersion(hdr[offset:offset+layout.VersionLen], layout, epoch) {
		return info, false
	}
	offset += layout.VersionLen

	for _, field := range layout.Fields {
		if offset+field.Size > len(hdr) {
			return info, false
		}
		value := readUintBE(hdr[offset : offset+field.Size])
		switch field.Kind {
		case handshakeFieldLen:
			if value < uint32(layout.LenOffset) || value > uint32(^uint16(0)) {
				return info, false
			}
			info.HasTimestampPaddingLen = true
			info.TimestampPaddingLen = uint16(value - uint32(layout.LenOffset))
		case handshakeFieldFixID, handshakeFieldID1, handshakeFieldID2:
			if value != field.Value {
				return info, false
			}
		case handshakeFieldEpochID:
			if value != truncateUint(epoch, field.Size) {
				return info, false
			}
		case handshakeFieldUTC:
			now := time.Now().Unix()
			utc := int64(value)
			maxDriftSec := int64(constants.MaxTimeDrift / 1000000000)
			if utc < now-maxDriftSec || utc > now+maxDriftSec {
				return info, false
			}
		case handshakeFieldClientID, handshakeFieldIncID, handshakeFieldPacketID:
			// Client-selected values are carried for shape diversity; the server does not know them in advance.
		}
		offset += field.Size
	}
	return info, true
}

func validateVersion(got []byte, layout *handshakeLayout, epoch uint64) bool {
	switch layout.VersionKind {
	case versionNone:
		return len(got) == 0
	case versionUint32:
		return len(got) == 4 && binary.BigEndian.Uint32(got) == uint32(epoch)
	case versionInt16Triple:
		if len(got) != 6 {
			return false
		}
		segments := epochDecimalSegments(epoch, layout.VersionSegments)
		for i, segment := range segments {
			if binary.BigEndian.Uint16(got[i*2:i*2+2]) != uint16(segment) {
				return false
			}
		}
		return true
	case versionString:
		want := make([]byte, layout.VersionLen)
		copy(want, []byte(epochVersionString(epoch, layout.VersionSegments)))
		return hmac.Equal(got, want)
	default:
		return false
	}
}

func readUintBE(src []byte) uint32 {
	switch len(src) {
	case 1:
		return uint32(src[0])
	case 2:
		return uint32(binary.BigEndian.Uint16(src))
	case 4:
		return binary.BigEndian.Uint32(src)
	default:
		return 0
	}
}

func truncateUint(value uint64, size int) uint32 {
	switch size {
	case 1:
		return uint32(value & 0xff)
	case 2:
		return uint32(value & 0xffff)
	case 4:
		return uint32(value & 0xffffffff)
	default:
		return 0
	}
}

func ValidateHandshakeHeaderAuth(v uint64, rcvdHdr []byte) bool {
	if len(rcvdHdr) != constants.HandshakeObfPrefixSize {
		return false
	}
	expected := handshakeHeaderAuth(v, rcvdHdr[:constants.HandshakeObfHeaderSize])
	got := rcvdHdr[constants.HandshakeObfHeaderSize:]
	return hmac.Equal(expected, got)
}

func handshakeHeaderAuth(v uint64, hdr []byte) []byte {
	var key [8]byte
	binary.BigEndian.PutUint64(key[:], v)
	mac := hmac.New(sha256.New, key[:])
	mac.Write(hdr) //nolint:errcheck
	sum := mac.Sum(nil)
	return sum[:constants.HandshakeObfHeaderAuthSize]
}
